### ISSUE TITLE
Signature with indefinite length and Universal Tag 0

### ISSUE THREAD

**Issue by hawajrambo** [sop/asn1#12] opened 2019-04-29 22:15 UTC
Dear Developer,

The parser fails with the attached file, as it cannot parse indefinite length elements.
Here I read, the indefinite length elements are closed with 00 00
http://luca.ntop.org/Teaching/Appunti/asn1.html
So I fixed this with the following code:
    public static function expectFromDER(...
        if ($length->isIndefinite()) {
            // throw new DecodeException("DER encoding must have definite length.");
            $length= new Length(strpos($data, "\0\0", $idx) +2 -$idx, false); //$indefinite=false
Then it continues parsing elements with the correct length, until it reaches a NULL object: then it raises a new exception:
Fatal error: Uncaught UnexpectedValueException: Universal tag 0 not implemented.

Can you please fix the parser to be able to parse this file?
Thank you, 
Gabor

The attached file is valid:
openssl pkcs7 -in signatureWithIdefiniteLength.pkcs7 -inform DER -print

[signatureWithIdefiniteLength.zip](https://github.com/sop/asn1/files/3129372/signatureWithIdefiniteLength.zip)

**Comment by sop** [comment] 2019-04-30 06:01
Hi!

This is a known limitation as for now. ASN.1 DER encoding rules forbid the usage of indefinite encoding. See [X.690-0207.pdf](https://www.itu.int/ITU-T/studygroups/com17/languages/X.690-0207.pdf) chapter 10.1.
This is the first time i've encountered indefinite encoding in the wild. I might look into it and see if a non-strict support could be implemented easily.

**Comment by fantasya-pbem** [comment] 2019-05-03 13:48
Hi Joni!

I have the same issue (DER with indefinite length) with real-life data too.

I have added an openssl-asn1parsed DER PKCS7 containing an EnvelopedData structure with encoded XML.
[der-indefinite-length.txt](https://github.com/sop/asn1/files/3142128/der-indefinite-length.txt)

I have cleared some of the hex values with zeroes for privacy, but I think you get an idea how the DER looks like. Do you think there may be an easy fix for such format? I haven't tried the code from hawajrambo yet, just wanted to give you another example.

**Comment by sop** [comment] 2019-05-03 16:54
Hi!

I have an experimental branch with support for indefinite length encoding. Please see https://github.com/sop/asn1/tree/indefinite if that's any help in the meantime. I'll merge and publish when i have time to double check it.

**Comment by hawajrambo** [comment] 2019-05-04 22:35
Dear Joni!
I tested the "indefinite" branch against 1500 certificates from 70 different issuers, and it works 100%.
Thanks
Gabor

**Comment by sop** [comment] 2019-05-05 07:29
Thanks for testing out! I've now merged indefinite length support and released a tag into packagist.

**Closed by sop** 2019-05-05 07:29 UTC

**Comment by fantasya-pbem** [comment] 2019-05-06 14:15
Thank you very much Joni, I am now able to decode the indefinite length structure. I have another issue now, and I'm not yet sure what the cause is (problematic DER data or a bug in your code). I'd like to give you the file that has issues, shall I create a new issue?

**Comment by sop** [comment] 2019-05-06 15:33
No problem!
Please create a new issue and attach your data. Make sure there's no private information :).

**Comment by fantasya-pbem** [comment] 2019-05-06 17:33
Great! I will double-check the file that has issues and create a new issue if I cannot get rid of the problem. Nevertheless, I want to say a big THANK YOU VERY MUCH for your effort you put into this amazing piece of software!
